package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

/**
 * Carritos generated by hbm2java
 */
public class Carritos implements java.io.Serializable {

	private Integer carId;
	private Clientes clientes;
	private Productos productos;
	private int carNumprod;

	public Carritos() {
	}

	public Carritos(int carNumprod) {
		this.carNumprod = carNumprod;
	}

	public Carritos(Clientes clientes, Productos productos, int carNumprod) {
		this.clientes = clientes;
		this.productos = productos;
		this.carNumprod = carNumprod;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public int getCarNumprod() {
		return this.carNumprod;
	}

	public void setCarNumprod(int carNumprod) {
		this.carNumprod = carNumprod;
	}

}
