package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

/**
 * ClienteproductosId generated by hbm2java
 */
public class ClienteproductosId implements java.io.Serializable {

	private Integer cpProId;
	private Integer cpCliId;

	public ClienteproductosId() {
	}

	public ClienteproductosId(Integer cpProId, Integer cpCliId) {
		this.cpProId = cpProId;
		this.cpCliId = cpCliId;
	}

	public Integer getCpProId() {
		return this.cpProId;
	}

	public void setCpProId(Integer cpProId) {
		this.cpProId = cpProId;
	}

	public Integer getCpCliId() {
		return this.cpCliId;
	}

	public void setCpCliId(Integer cpCliId) {
		this.cpCliId = cpCliId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteproductosId))
			return false;
		ClienteproductosId castOther = (ClienteproductosId) other;

		return ((this.getCpProId() == castOther.getCpProId()) || (this.getCpProId() != null
				&& castOther.getCpProId() != null && this.getCpProId().equals(castOther.getCpProId())))
				&& ((this.getCpCliId() == castOther.getCpCliId()) || (this.getCpCliId() != null
						&& castOther.getCpCliId() != null && this.getCpCliId().equals(castOther.getCpCliId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCpProId() == null ? 0 : this.getCpProId().hashCode());
		result = 37 * result + (getCpCliId() == null ? 0 : this.getCpCliId().hashCode());
		return result;
	}

}
