package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

/**
 * Clienteproductos generated by hbm2java
 */
public class Clienteproductos implements java.io.Serializable {

	private ClienteproductosId id;
	private Clientes clientes;
	private Productos productos;

	public Clienteproductos() {
	}

	public Clienteproductos(ClienteproductosId id) {
		this.id = id;
	}

	public Clienteproductos(ClienteproductosId id, Clientes clientes, Productos productos) {
		this.id = id;
		this.clientes = clientes;
		this.productos = productos;
	}

	public ClienteproductosId getId() {
		return this.id;
	}

	public void setId(ClienteproductosId id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

}
