package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer cliId;
	private String cliNombre;
	private String cliApellido1;
	private String cliApellido2;
	private Date cliFechaNacimiento;
	private String cliEmail;
	private String cliPwd;
	private Set carritoses = new HashSet(0);
	private Set clienteproductoses = new HashSet(0);
	private Set tarjetasbancariases = new HashSet(0);
	private Set comprasrealizadases = new HashSet(0);
	private Set clientesdireccioneses = new HashSet(0);

	public Clientes() {
	}
	
	

	public Clientes(String cliNombre, String cliApellido1, String cliApellido2, Date cliFechaNacimiento,
			String cliEmail, String cliPwd) {
		this.cliNombre = cliNombre;
		this.cliApellido1 = cliApellido1;
		this.cliApellido2 = cliApellido2;
		this.cliFechaNacimiento = cliFechaNacimiento;
		this.cliEmail = cliEmail;
		this.cliPwd = cliPwd;
	}

	public Clientes(String cliNombre, String cliApellido1, String cliApellido2, Date cliFechaNacimiento,
			String cliEmail, String cliPwd, Set carritoses, Set clienteproductoses, Set tarjetasbancariases,
			Set comprasrealizadases, Set clientesdireccioneses) {
		this.cliNombre = cliNombre;
		this.cliApellido1 = cliApellido1;
		this.cliApellido2 = cliApellido2;
		this.cliFechaNacimiento = cliFechaNacimiento;
		this.cliEmail = cliEmail;
		this.cliPwd = cliPwd;
		this.carritoses = carritoses;
		this.clienteproductoses = clienteproductoses;
		this.tarjetasbancariases = tarjetasbancariases;
		this.comprasrealizadases = comprasrealizadases;
		this.clientesdireccioneses = clientesdireccioneses;
	}

	public Integer getCliId() {
		return this.cliId;
	}

	public void setCliId(Integer cliId) {
		this.cliId = cliId;
	}

	public String getCliNombre() {
		return this.cliNombre;
	}

	public void setCliNombre(String cliNombre) {
		this.cliNombre = cliNombre;
	}

	public String getCliApellido1() {
		return this.cliApellido1;
	}

	public void setCliApellido1(String cliApellido1) {
		this.cliApellido1 = cliApellido1;
	}

	public String getCliApellido2() {
		return this.cliApellido2;
	}

	public void setCliApellido2(String cliApellido2) {
		this.cliApellido2 = cliApellido2;
	}

	public Date getCliFechaNacimiento() {
		return this.cliFechaNacimiento;
	}

	public void setCliFechaNacimiento(Date cliFechaNacimiento) {
		this.cliFechaNacimiento = cliFechaNacimiento;
	}

	public String getCliEmail() {
		return this.cliEmail;
	}

	public void setCliEmail(String cliEmail) {
		this.cliEmail = cliEmail;
	}

	public String getCliPwd() {
		return this.cliPwd;
	}

	public void setCliPwd(String cliPwd) {
		this.cliPwd = cliPwd;
	}

	public Set getCarritoses() {
		return this.carritoses;
	}

	public void setCarritoses(Set carritoses) {
		this.carritoses = carritoses;
	}

	public Set getClienteproductoses() {
		return this.clienteproductoses;
	}

	public void setClienteproductoses(Set clienteproductoses) {
		this.clienteproductoses = clienteproductoses;
	}

	public Set getTarjetasbancariases() {
		return this.tarjetasbancariases;
	}

	public void setTarjetasbancariases(Set tarjetasbancariases) {
		this.tarjetasbancariases = tarjetasbancariases;
	}

	public Set getComprasrealizadases() {
		return this.comprasrealizadases;
	}

	public void setComprasrealizadases(Set comprasrealizadases) {
		this.comprasrealizadases = comprasrealizadases;
	}

	public Set getClientesdireccioneses() {
		return this.clientesdireccioneses;
	}

	public void setClientesdireccioneses(Set clientesdireccioneses) {
		this.clientesdireccioneses = clientesdireccioneses;
	}

}
