package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

/**
 * Clientesdirecciones generated by hbm2java
 */
public class Clientesdirecciones implements java.io.Serializable {

	private ClientesdireccionesId id;
	private Clientes clientes;
	private Direcciones direcciones;

	public Clientesdirecciones() {
	}

	public Clientesdirecciones(ClientesdireccionesId id) {
		this.id = id;
	}

	public Clientesdirecciones(ClientesdireccionesId id, Clientes clientes, Direcciones direcciones) {
		this.id = id;
		this.clientes = clientes;
		this.direcciones = direcciones;
	}

	public ClientesdireccionesId getId() {
		return this.id;
	}

	public void setId(ClientesdireccionesId id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Direcciones getDirecciones() {
		return this.direcciones;
	}

	public void setDirecciones(Direcciones direcciones) {
		this.direcciones = direcciones;
	}

}
