package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Direcciones generated by hbm2java
 */
public class Direcciones implements java.io.Serializable {

	private Integer dirId;
	private int dirCodigoPostal;
	private String dirLocalidad;
	private String dirCalle;
	private int dirNumero;
	private String dirPiso;
	private String dirLetra;
	private Set clientesdireccioneses = new HashSet(0);

	public Direcciones() {
	}

	public Direcciones(int dirCodigoPostal, String dirLocalidad, String dirCalle, int dirNumero) {
		this.dirCodigoPostal = dirCodigoPostal;
		this.dirLocalidad = dirLocalidad;
		this.dirCalle = dirCalle;
		this.dirNumero = dirNumero;
	}

	public Direcciones(int dirCodigoPostal, String dirLocalidad, String dirCalle, int dirNumero, String dirPiso,
			String dirLetra, Set clientesdireccioneses) {
		this.dirCodigoPostal = dirCodigoPostal;
		this.dirLocalidad = dirLocalidad;
		this.dirCalle = dirCalle;
		this.dirNumero = dirNumero;
		this.dirPiso = dirPiso;
		this.dirLetra = dirLetra;
		this.clientesdireccioneses = clientesdireccioneses;
	}

	public Integer getDirId() {
		return this.dirId;
	}

	public void setDirId(Integer dirId) {
		this.dirId = dirId;
	}

	public int getDirCodigoPostal() {
		return this.dirCodigoPostal;
	}

	public void setDirCodigoPostal(int dirCodigoPostal) {
		this.dirCodigoPostal = dirCodigoPostal;
	}

	public String getDirLocalidad() {
		return this.dirLocalidad;
	}

	public void setDirLocalidad(String dirLocalidad) {
		this.dirLocalidad = dirLocalidad;
	}

	public String getDirCalle() {
		return this.dirCalle;
	}

	public void setDirCalle(String dirCalle) {
		this.dirCalle = dirCalle;
	}

	public int getDirNumero() {
		return this.dirNumero;
	}

	public void setDirNumero(int dirNumero) {
		this.dirNumero = dirNumero;
	}

	public String getDirPiso() {
		return this.dirPiso;
	}

	public void setDirPiso(String dirPiso) {
		this.dirPiso = dirPiso;
	}

	public String getDirLetra() {
		return this.dirLetra;
	}

	public void setDirLetra(String dirLetra) {
		this.dirLetra = dirLetra;
	}

	public Set getClientesdireccioneses() {
		return this.clientesdireccioneses;
	}

	public void setClientesdireccioneses(Set clientesdireccioneses) {
		this.clientesdireccioneses = clientesdireccioneses;
	}

}
