package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer proId;
	private String proNombre;
	private String proFoto;
	private String proDescripcion;
	private double proPrecio;
	private int proStock;
	private Set carritoses = new HashSet(0);
	private Set clienteproductoses = new HashSet(0);
	private Set comprasrealizadases = new HashSet(0);

	public Productos() {
	}

	public Productos(String proNombre, String proFoto, String proDescripcion, double proPrecio, int proStock) {
		this.proNombre = proNombre;
		this.proFoto = proFoto;
		this.proDescripcion = proDescripcion;
		this.proPrecio = proPrecio;
		this.proStock = proStock;
	}

	public Productos(String proNombre, String proFoto, String proDescripcion, double proPrecio, int proStock,
			Set carritoses, Set clienteproductoses, Set comprasrealizadases) {
		this.proNombre = proNombre;
		this.proFoto = proFoto;
		this.proDescripcion = proDescripcion;
		this.proPrecio = proPrecio;
		this.proStock = proStock;
		this.carritoses = carritoses;
		this.clienteproductoses = clienteproductoses;
		this.comprasrealizadases = comprasrealizadases;
	}

	public Integer getProId() {
		return this.proId;
	}

	public void setProId(Integer proId) {
		this.proId = proId;
	}

	public String getProNombre() {
		return this.proNombre;
	}

	public void setProNombre(String proNombre) {
		this.proNombre = proNombre;
	}

	public String getProFoto() {
		return this.proFoto;
	}

	public void setProFoto(String proFoto) {
		this.proFoto = proFoto;
	}

	public String getProDescripcion() {
		return this.proDescripcion;
	}

	public void setProDescripcion(String proDescripcion) {
		this.proDescripcion = proDescripcion;
	}

	public double getProPrecio() {
		return this.proPrecio;
	}

	public void setProPrecio(double proPrecio) {
		this.proPrecio = proPrecio;
	}

	public int getProStock() {
		return this.proStock;
	}

	public void setProStock(int proStock) {
		this.proStock = proStock;
	}

	public Set getCarritoses() {
		return this.carritoses;
	}

	public void setCarritoses(Set carritoses) {
		this.carritoses = carritoses;
	}

	public Set getClienteproductoses() {
		return this.clienteproductoses;
	}

	public void setClienteproductoses(Set clienteproductoses) {
		this.clienteproductoses = clienteproductoses;
	}

	public Set getComprasrealizadases() {
		return this.comprasrealizadases;
	}

	public void setComprasrealizadases(Set comprasrealizadases) {
		this.comprasrealizadases = comprasrealizadases;
	}

}
