package entidades;
// Generated 8 feb 2023 11:39:24 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetasbancarias generated by hbm2java
 */
public class Tarjetasbancarias implements java.io.Serializable {

	private Integer TId;
	private Clientes clientes;
	private String TNumTarjeta;
	private String TNombreTitular;
	private Date TFechaCaducidad;
	private int TCvv;
	private Set comprasrealizadases = new HashSet(0);

	public Tarjetasbancarias() {
	}

	public Tarjetasbancarias(String TNumTarjeta, String TNombreTitular, Date TFechaCaducidad, int TCvv) {
		this.TNumTarjeta = TNumTarjeta;
		this.TNombreTitular = TNombreTitular;
		this.TFechaCaducidad = TFechaCaducidad;
		this.TCvv = TCvv;
	}

	public Tarjetasbancarias(Clientes clientes, String TNumTarjeta, String TNombreTitular, Date TFechaCaducidad,
			int TCvv, Set comprasrealizadases) {
		this.clientes = clientes;
		this.TNumTarjeta = TNumTarjeta;
		this.TNombreTitular = TNombreTitular;
		this.TFechaCaducidad = TFechaCaducidad;
		this.TCvv = TCvv;
		this.comprasrealizadases = comprasrealizadases;
	}

	public Integer getTId() {
		return this.TId;
	}

	public void setTId(Integer TId) {
		this.TId = TId;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getTNumTarjeta() {
		return this.TNumTarjeta;
	}

	public void setTNumTarjeta(String TNumTarjeta) {
		this.TNumTarjeta = TNumTarjeta;
	}

	public String getTNombreTitular() {
		return this.TNombreTitular;
	}

	public void setTNombreTitular(String TNombreTitular) {
		this.TNombreTitular = TNombreTitular;
	}

	public Date getTFechaCaducidad() {
		return this.TFechaCaducidad;
	}

	public void setTFechaCaducidad(Date TFechaCaducidad) {
		this.TFechaCaducidad = TFechaCaducidad;
	}

	public int getTCvv() {
		return this.TCvv;
	}

	public void setTCvv(int TCvv) {
		this.TCvv = TCvv;
	}

	public Set getComprasrealizadases() {
		return this.comprasrealizadases;
	}

	public void setComprasrealizadases(Set comprasrealizadases) {
		this.comprasrealizadases = comprasrealizadases;
	}

}
